RFC: Add the ability to retrieve the raw camera data
j5api/j5-zoloto pull request #5
Opened 2022-01-25 23:20 UTC by RealOrangeOne

This is the form of a 2d numpy array

## Checklist

- [ ] I have updated the relevant documentation
- [ ] I have added the `semver-major`, `semver-minor` or `semver-patch` label as appropriate
- [x] I would like multiple reviewers to approve my code before merging

## Why do you want to make these changes?

For uses outside zoloto, it's useful to read the raw pixel data from the camera without any additional processing.

## Which parts of the codebase do your changes affect?

Basically everything.

## How do your changes affect student or volunteer experience?

Moar data = moar gud

## Are your changes related to any existing issues or PRs? How so?

N/A

2022-01-26 08:06 UTC, trickeydan approved these changes
LGTM. Not sure it changes "everything" like your PR claims though.

CI is failing on linting, bit I'm happy for this to be merged once that is fixed.

2022-02-01 20:34 UTC, trickeydan requested changes

2022-02-01 20:34 UTC, trickeydan commented on stubs/numpy.py
> +ndarray = Any  # type: ignore
No

2022-02-01 20:40 UTC, RealOrangeOne commented on stubs/numpy.py
> +ndarray = Any  # type: ignore
Yes

2022-02-01 20:41 UTC, merged